from enum import Enum


class AutomationStatus(str, Enum):
    DRAFT = "DRAFT"
    TESTING = "TESTING"
    PUBLISHED = "PUBLISHED"
    DISABLED = "DISABLED"
    BROKEN = "BROKEN"
    ARCHIVED = "ARCHIVED"


class ExecutionStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ExecutionAutomationStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    RETRYING = "RETRYING"
    SUCCEEDED = "SUCCEEDED"
    REMOVED = "REMOVED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ExecutionStage(str, Enum):
    CREATED = "CREATED"
    NAVIGATING = "NAVIGATING"
    AUTHENTICATING = "AUTHENTICATING"
    FILTERING = "FILTERING"
    SEARCHING = "SEARCHING"
    WAITING_RESULT = "WAITING_RESULT"
    EXPORTING = "EXPORTING"
    WAITING_PROCESSING = "WAITING_PROCESSING"
    DOWNLOADING = "DOWNLOADING"
    VALIDATING = "VALIDATING"
    RENAMING = "RENAMING"
    COPYING = "COPYING"
    FINISHED = "FINISHED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class WorkerStatus(str, Enum):
    ONLINE = "ONLINE"
    OFFLINE = "OFFLINE"
