param(
    [Parameter(Mandatory=$true)]
    [string]$CurrentTask,

    [Parameter(Mandatory=$true)]
    [string]$NextTask,

    [string]$Evidence = "",

    [string]$Status = "IN_PROGRESS"
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

$branch = (git branch --show-current).Trim()
$commit = (git rev-parse --short HEAD).Trim()
$commitFull = (git rev-parse HEAD).Trim()

if (-not $branch) {
    throw "Git branch not detected."
}

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"

$content = @"
# Nexer — Checkpoint

Generated by scripts/handoff.ps1

- Timestamp: $timestamp
- Branch: $branch
- Commit: $commitFull
- Status: $Status

## Current task

$CurrentTask

## Next task

$NextTask

## Evidence

$Evidence

## Resume command

Continue the Nexer development from this repository state. Read MASTER_PLAN.md, docs/development/CURRENT_STATE.md, HANDOFF.md and this checkpoint. Verify GitHub/CI and continue with the next microtask. Do not modify master/legacy. Use TDD for new functional code.
"@

$checkpointPath = Join-Path $repoRoot "docs/development/LAST_CHECKPOINT.md"
Set-Content -Path $checkpointPath -Value $content -Encoding UTF8

Write-Host "Checkpoint written: $checkpointPath"
Write-Host "Branch: $branch"
Write-Host "Commit: $commit"
